# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "UpliftGames/rojo@7.4.0-uplift.syncback.rc.20"
pesde = "pesde-pkg/pesde@0.6.0-rc.6+registry.0.2.0-rc.2"
blink = "1Axen/blink@0.15.4"
lune = "lune-org/lune@0.8.9"
selene = "Kampfkarren/selene@0.28.0"
StyLua = "JohnnyMorganz/StyLua@2.0.2"